/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author darlanaraujo
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        
        setExtendedState(MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        lblHorario = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        lblAcesso = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnLogoff = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jCalendar2 = new com.toedter.calendar.JCalendar();
        jLabel12 = new javax.swing.JLabel();
        telaFundo = new javax.swing.JDesktopPane();
        lblFundo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        menuCadHospede = new javax.swing.JMenuItem();
        menuConHospedes = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        menuCadQuatos = new javax.swing.JMenuItem();
        menuConQuatos = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        menuCadFuncionarios = new javax.swing.JMenuItem();
        menuConFuncionarios = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        menuCadFornecedores = new javax.swing.JMenuItem();
        menuConFornecedores = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        menuCadProdutos = new javax.swing.JMenuItem();
        menuConProdutos = new javax.swing.JMenuItem();
        jMenu15 = new javax.swing.JMenu();
        menuCadServicos = new javax.swing.JMenuItem();
        menuConServicos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuCadReserva = new javax.swing.JMenuItem();
        menuConReserva = new javax.swing.JMenuItem();
        menuFinReserva = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuVenProduto = new javax.swing.JMenuItem();
        menuVenServico = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        menuCadConPagar = new javax.swing.JMenuItem();
        menuConConPagar = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        menuCadConReceber = new javax.swing.JMenuItem();
        menuConConReceber = new javax.swing.JMenuItem();
        menuBalanco = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu17 = new javax.swing.JMenu();
        menuRelaResQDisp = new javax.swing.JMenuItem();
        menuRelaResQOcu = new javax.swing.JMenuItem();
        menuRelaResFut = new javax.swing.JMenuItem();
        jMenu18 = new javax.swing.JMenu();
        menuRelaVenProdutos = new javax.swing.JMenuItem();
        menuRelaVenServicos = new javax.swing.JMenuItem();
        menuRelaHospedes = new javax.swing.JMenuItem();
        menuRelaFuncionarios = new javax.swing.JMenuItem();
        menuRelaFornecedores = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        menuFazBackup = new javax.swing.JMenuItem();
        menuResBackup = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenu20 = new javax.swing.JMenu();
        menuAddFundo = new javax.swing.JMenuItem();
        menuRemFundo = new javax.swing.JMenuItem();
        menuResPadrao = new javax.swing.JMenuItem();
        menuSobSistema = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hotel Imperial - Tela Principal");

        jLabel1.setText("Sistema Hotel Projeto PIM - Sistema desenvolvido por Darlan Araujo - Todos os direitos reservados - 2021");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(jLabel1)
                .addContainerGap(403, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_m.png"))); // NOI18N

        lblHorario.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lblHorario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHorario.setText("horário do sistema");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel5.setText("Usuário:");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel6.setText("Cargo:");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel7.setText("G. Acesso:");

        lblUsuario.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(51, 51, 51));
        lblUsuario.setText("Nome");

        lblCargo.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        lblCargo.setForeground(new java.awt.Color(51, 51, 51));
        lblCargo.setText("texto");

        lblAcesso.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        lblAcesso.setForeground(new java.awt.Color(51, 51, 51));
        lblAcesso.setText("texto");

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel11.setText("Check-in de Hospedes");

        btnLogoff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_entrar.png"))); // NOI18N
        btnLogoff.setText("Logoff");
        btnLogoff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoffActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setText("HOTEL IMPERIAL");

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel14.setText("PEIXOTO ARAUJO");

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel12.setText("Check-out de Hospedes");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addComponent(jSeparator5)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCargo)
                            .addComponent(lblUsuario)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(lblAcesso)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHorario)
                    .addComponent(btnLogoff, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel3))
                .addGap(100, 100, 100))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jSeparator6)
                .addContainerGap())
            .addComponent(jSeparator4)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCalendar2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(70, 70, 70))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(19, 19, 19)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHorario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblCargo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblAcesso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogoff, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCalendar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel2);

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoPadrao.jpg"))); // NOI18N
        lblFundo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblFundo.setMaximumSize(new java.awt.Dimension(1920, 1080));
        lblFundo.setMinimumSize(new java.awt.Dimension(1920, 1080));

        telaFundo.setLayer(lblFundo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout telaFundoLayout = new javax.swing.GroupLayout(telaFundo);
        telaFundo.setLayout(telaFundoLayout);
        telaFundoLayout.setHorizontalGroup(
            telaFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        telaFundoLayout.setVerticalGroup(
            telaFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastro.png"))); // NOI18N
        jMenu1.setText("Cadastros    |");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_hospede.png"))); // NOI18N
        jMenu9.setText("Hospedes");
        jMenu9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuCadHospede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_salvar.png"))); // NOI18N
        menuCadHospede.setText("Cadastrar");
        menuCadHospede.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu9.add(menuCadHospede);

        menuConHospedes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_buscar.png"))); // NOI18N
        menuConHospedes.setText("Consultar");
        menuConHospedes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu9.add(menuConHospedes);

        jMenu1.add(jMenu9);

        jMenu10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_quarto.png"))); // NOI18N
        jMenu10.setText("Quartos");
        jMenu10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuCadQuatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_quarto.png"))); // NOI18N
        menuCadQuatos.setText("Cadastrar");
        menuCadQuatos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu10.add(menuCadQuatos);

        menuConQuatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/buscar.png"))); // NOI18N
        menuConQuatos.setText("Consultar");
        menuConQuatos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuConQuatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConQuatosActionPerformed(evt);
            }
        });
        jMenu10.add(menuConQuatos);

        jMenu1.add(jMenu10);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_funcionario.png"))); // NOI18N
        jMenu8.setText("Funcionários");
        jMenu8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuCadFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_salvar.png"))); // NOI18N
        menuCadFuncionarios.setText("Cadastrar");
        menuCadFuncionarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuCadFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadFuncionariosActionPerformed(evt);
            }
        });
        jMenu8.add(menuCadFuncionarios);

        menuConFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_buscar.png"))); // NOI18N
        menuConFuncionarios.setText("Consultar");
        menuConFuncionarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu8.add(menuConFuncionarios);

        jMenu1.add(jMenu8);

        jMenu11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_fornecedor.png"))); // NOI18N
        jMenu11.setText("Fornecedores");
        jMenu11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuCadFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_salvar.png"))); // NOI18N
        menuCadFornecedores.setText("Cadastrar");
        menuCadFornecedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu11.add(menuCadFornecedores);

        menuConFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_buscar.png"))); // NOI18N
        menuConFornecedores.setText("Consultar");
        menuConFornecedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu11.add(menuConFornecedores);

        jMenu1.add(jMenu11);

        jMenu12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_produtos.png"))); // NOI18N
        jMenu12.setText("Produtos");
        jMenu12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuCadProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_vender.png"))); // NOI18N
        menuCadProdutos.setText("Cadastrar");
        menuCadProdutos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu12.add(menuCadProdutos);

        menuConProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/buscar.png"))); // NOI18N
        menuConProdutos.setText("Consultar");
        menuConProdutos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu12.add(menuConProdutos);

        jMenu1.add(jMenu12);

        jMenu15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_servicos.png"))); // NOI18N
        jMenu15.setText("Serviços");
        jMenu15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuCadServicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_vender.png"))); // NOI18N
        menuCadServicos.setText("Cadastrar");
        menuCadServicos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuCadServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadServicosActionPerformed(evt);
            }
        });
        jMenu15.add(menuCadServicos);

        menuConServicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/buscar.png"))); // NOI18N
        menuConServicos.setText("Consultar");
        menuConServicos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu15.add(menuConServicos);

        jMenu1.add(jMenu15);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/reservas.png"))); // NOI18N
        jMenu2.setText("Reservas   |");
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuCadReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_checkin.png"))); // NOI18N
        menuCadReserva.setText("Cadastrar Reserva");
        menuCadReserva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu2.add(menuCadReserva);

        menuConReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_Con_checkin.png"))); // NOI18N
        menuConReserva.setText("Consultar Reserva");
        menuConReserva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu2.add(menuConReserva);

        menuFinReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_checkout.png"))); // NOI18N
        menuFinReserva.setText("Finalizar Reserva");
        menuFinReserva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu2.add(menuFinReserva);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/consumo.png"))); // NOI18N
        jMenu3.setText("Vendas   |");
        jMenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuVenProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_produtos.png"))); // NOI18N
        menuVenProduto.setText("Produtos");
        menuVenProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu3.add(menuVenProduto);

        menuVenServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_servicos.png"))); // NOI18N
        menuVenServico.setText("Serviços");
        menuVenServico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu3.add(menuVenServico);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/financeiro.png"))); // NOI18N
        jMenu4.setText("Financeiro   |");
        jMenu4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenu13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_conta_paga.png"))); // NOI18N
        jMenu13.setText("Contas a Pagar");
        jMenu13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuCadConPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_cad_conta.png"))); // NOI18N
        menuCadConPagar.setText("Cadastrar");
        menuCadConPagar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu13.add(menuCadConPagar);

        menuConConPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_conta_consulta.png"))); // NOI18N
        menuConConPagar.setText("Consultar");
        menuConConPagar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuConConPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConConPagarActionPerformed(evt);
            }
        });
        jMenu13.add(menuConConPagar);

        jMenu4.add(jMenu13);

        jMenu14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_conta_recebe.png"))); // NOI18N
        jMenu14.setText("Contas a Receber");
        jMenu14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuCadConReceber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_cad_conta.png"))); // NOI18N
        menuCadConReceber.setText("Cadastrar");
        menuCadConReceber.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu14.add(menuCadConReceber);

        menuConConReceber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_conta_consulta.png"))); // NOI18N
        menuConConReceber.setText("Consultar");
        menuConConReceber.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu14.add(menuConConReceber);

        jMenu4.add(jMenu14);

        menuBalanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_balanco.png"))); // NOI18N
        menuBalanco.setText("Balanço");
        menuBalanco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu4.add(menuBalanco);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatorios.png"))); // NOI18N
        jMenu5.setText("Relatórios   |");
        jMenu5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenu16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_rela_financeiro.png"))); // NOI18N
        jMenu16.setText("Financeiro");
        jMenu16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_rela_financeiro.png"))); // NOI18N
        jMenuItem3.setText("Contas a Pagar");
        jMenuItem3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu16.add(jMenuItem3);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_rela_financeiro.png"))); // NOI18N
        jMenuItem4.setText("Contas a Receber");
        jMenuItem4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu16.add(jMenuItem4);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_rela_financeiro.png"))); // NOI18N
        jMenuItem5.setText("Balanço");
        jMenuItem5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu16.add(jMenuItem5);

        jMenu5.add(jMenu16);

        jMenu17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_rela_reserva.png"))); // NOI18N
        jMenu17.setText("Reservas");
        jMenu17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuRelaResQDisp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_rela_reserva.png"))); // NOI18N
        menuRelaResQDisp.setText("Quartos Disponiveis");
        menuRelaResQDisp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu17.add(menuRelaResQDisp);

        menuRelaResQOcu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_rela_reserva.png"))); // NOI18N
        menuRelaResQOcu.setText("Quartos Ocupados");
        menuRelaResQOcu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu17.add(menuRelaResQOcu);

        menuRelaResFut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_rela_reserva.png"))); // NOI18N
        menuRelaResFut.setText("Reservas Futuras");
        menuRelaResFut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu17.add(menuRelaResFut);

        jMenu5.add(jMenu17);

        jMenu18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_rela_produto.png"))); // NOI18N
        jMenu18.setText("Vendas");
        jMenu18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuRelaVenProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_rela_produto.png"))); // NOI18N
        menuRelaVenProdutos.setText("Produtos");
        menuRelaVenProdutos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu18.add(menuRelaVenProdutos);

        menuRelaVenServicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_rela_produto.png"))); // NOI18N
        menuRelaVenServicos.setText("Serviços");
        menuRelaVenServicos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu18.add(menuRelaVenServicos);

        jMenu5.add(jMenu18);

        menuRelaHospedes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_rela_pessoas.png"))); // NOI18N
        menuRelaHospedes.setText("Hospedes");
        menuRelaHospedes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu5.add(menuRelaHospedes);

        menuRelaFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_rela_pessoas.png"))); // NOI18N
        menuRelaFuncionarios.setText("Funcionários");
        menuRelaFuncionarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuRelaFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelaFuncionariosActionPerformed(evt);
            }
        });
        jMenu5.add(menuRelaFuncionarios);

        menuRelaFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_rela_pessoas.png"))); // NOI18N
        menuRelaFornecedores.setText("Fornecedores");
        menuRelaFornecedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu5.add(menuRelaFornecedores);

        jMenuBar1.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seguranca.png"))); // NOI18N
        jMenu6.setText("Segurança   |");
        jMenu6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuFazBackup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_backup.png"))); // NOI18N
        menuFazBackup.setText("Fazer backup");
        menuFazBackup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu6.add(menuFazBackup);

        menuResBackup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_restaura.png"))); // NOI18N
        menuResBackup.setText("Restaurar Backup");
        menuResBackup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu6.add(menuResBackup);

        jMenuBar1.add(jMenu6);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ferramentas.png"))); // NOI18N
        jMenu7.setText("Ferramentas   |");
        jMenu7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenu20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_img.png"))); // NOI18N
        jMenu20.setText("Tela de Fundo");
        jMenu20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuAddFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_img_add.png"))); // NOI18N
        menuAddFundo.setText("Add Imagem");
        menuAddFundo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu20.add(menuAddFundo);

        menuRemFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_img_remove.png"))); // NOI18N
        menuRemFundo.setText("Remover Imagem");
        menuRemFundo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu20.add(menuRemFundo);

        menuResPadrao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_img_padrao.png"))); // NOI18N
        menuResPadrao.setText("Restaurar Padrão");
        menuResPadrao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu20.add(menuResPadrao);

        jMenu7.add(jMenu20);

        menuSobSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_sistema.png"))); // NOI18N
        menuSobSistema.setText("Sobre o sistema");
        menuSobSistema.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu7.add(menuSobSistema);

        jMenuBar1.add(jMenu7);

        menuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair.png"))); // NOI18N
        menuSair.setText("Sair");
        menuSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(telaFundo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                    .addComponent(telaFundo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuConQuatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConQuatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuConQuatosActionPerformed

    private void menuCadServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadServicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadServicosActionPerformed

    private void menuConConPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConConPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuConConPagarActionPerformed

    private void menuRelaFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelaFuncionariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuRelaFuncionariosActionPerformed

    private void btnLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoffActionPerformed

    private void menuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSairMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuSairMouseClicked

    private void menuCadFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadFuncionariosActionPerformed
        // TODO add your handling code here:
        TelaCadFuncionario tela = new TelaCadFuncionario();
        telaFundo.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_menuCadFuncionariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogoff;
    private com.toedter.calendar.JCalendar jCalendar1;
    private com.toedter.calendar.JCalendar jCalendar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu20;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblAcesso;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblHorario;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenuItem menuAddFundo;
    private javax.swing.JMenuItem menuBalanco;
    private javax.swing.JMenuItem menuCadConPagar;
    private javax.swing.JMenuItem menuCadConReceber;
    private javax.swing.JMenuItem menuCadFornecedores;
    private javax.swing.JMenuItem menuCadFuncionarios;
    private javax.swing.JMenuItem menuCadHospede;
    private javax.swing.JMenuItem menuCadProdutos;
    private javax.swing.JMenuItem menuCadQuatos;
    private javax.swing.JMenuItem menuCadReserva;
    private javax.swing.JMenuItem menuCadServicos;
    private javax.swing.JMenuItem menuConConPagar;
    private javax.swing.JMenuItem menuConConReceber;
    private javax.swing.JMenuItem menuConFornecedores;
    private javax.swing.JMenuItem menuConFuncionarios;
    private javax.swing.JMenuItem menuConHospedes;
    private javax.swing.JMenuItem menuConProdutos;
    private javax.swing.JMenuItem menuConQuatos;
    private javax.swing.JMenuItem menuConReserva;
    private javax.swing.JMenuItem menuConServicos;
    private javax.swing.JMenuItem menuFazBackup;
    private javax.swing.JMenuItem menuFinReserva;
    private javax.swing.JMenuItem menuRelaFornecedores;
    private javax.swing.JMenuItem menuRelaFuncionarios;
    private javax.swing.JMenuItem menuRelaHospedes;
    private javax.swing.JMenuItem menuRelaResFut;
    private javax.swing.JMenuItem menuRelaResQDisp;
    private javax.swing.JMenuItem menuRelaResQOcu;
    private javax.swing.JMenuItem menuRelaVenProdutos;
    private javax.swing.JMenuItem menuRelaVenServicos;
    private javax.swing.JMenuItem menuRemFundo;
    private javax.swing.JMenuItem menuResBackup;
    private javax.swing.JMenuItem menuResPadrao;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenuItem menuSobSistema;
    private javax.swing.JMenuItem menuVenProduto;
    private javax.swing.JMenuItem menuVenServico;
    private javax.swing.JDesktopPane telaFundo;
    // End of variables declaration//GEN-END:variables
}
